// Synthetic data for mockup G. No real identities. Times are minutes from "now".
// Shapes follow /api/overview after presentation: meters (used %), balances, banked resets.
export const now = new Date(2026, 9, 3, 14, 0).getTime();
const min = 60_000;
export const at = (minutes) => now + minutes * min;

export const providers = [
  { id: "claude", name: "Claude" },
  { id: "codex", name: "Codex" },
  { id: "cursor", name: "Cursor" },
  { id: "grok", name: "Grok" },
  { id: "antigravity", name: "Antigravity" },
  { id: "copilot", name: "Copilot" },
  { id: "vercel_ai_gateway", name: "Vercel AI Gateway" },
];

// status: active | paused | disconnected | failed | stale
export const accounts = [
  {
    id: "cl-1",
    provider: "claude",
    name: "Personal",
    plan: "Max",
    identity: "maverick@example.com",
    status: "active",
    refreshed: -6,
    meters: [
      { key: "session", label: "Session", window: "5 hours", used: 64, resets: 22 },
      {
        key: "weekly",
        label: "Weekly",
        window: "all models",
        used: 81,
        resets: 2 * 1440 + 300,
        primary: true,
      },
      { key: "fable", label: "Weekly", window: "Fable", used: 91, resets: 2 * 1440 + 300 },
    ],
    banked: { label: "Reset Grant", count: 1, expiries: [19 * 1440] },
  },
  {
    id: "cl-2",
    provider: "claude",
    name: "Work",
    plan: "Team",
    identity: "maverick@acme.example",
    status: "active",
    refreshed: -4,
    meters: [
      { key: "session", label: "Session", window: "5 hours", used: 12, resets: 230 },
      {
        key: "weekly",
        label: "Weekly",
        window: "all models",
        used: 34,
        resets: 5 * 1440 + 60,
        primary: true,
      },
      { key: "fable", label: "Weekly", window: "Fable", used: 28, resets: 5 * 1440 + 60 },
    ],
    banked: { label: "Reset Grant", count: 0, expiries: [] },
  },
  {
    id: "cl-3",
    provider: "claude",
    name: "Side Project",
    plan: "Pro",
    identity: "side@example.com",
    status: "active",
    refreshed: -9,
    meters: [
      {
        key: "session",
        label: "Session",
        window: "5 hours",
        used: null,
        resets: null,
        notStarted: true,
      },
      {
        key: "weekly",
        label: "Weekly",
        window: "all models",
        used: 8,
        resets: 6 * 1440 + 600,
        primary: true,
      },
    ],
    banked: null,
  },
  {
    id: "cx-1",
    provider: "codex",
    name: "Personal",
    plan: "Pro",
    identity: "maverick@example.com",
    status: "active",
    refreshed: -11,
    meters: [
      {
        key: "weekly",
        label: "Weekly",
        window: "7 days",
        used: 24,
        resets: 5 * 1440 + 660,
        primary: true,
      },
    ],
    balances: [{ label: "Credits", value: 61068.39, unit: "credits" }],
    banked: { label: "Reset Credit", count: 3, expiries: [2 * 1440 + 660, 20 * 1440, 27 * 1440] },
    hold: true,
  },
  {
    id: "cx-2",
    provider: "codex",
    name: "Work",
    plan: "Business",
    identity: "maverick@acme.example",
    status: "paused",
    refreshed: -1640,
    meters: [
      { key: "session", label: "Session", window: "5 hours", used: 61, resets: 105 },
      {
        key: "weekly",
        label: "Weekly",
        window: "7 days",
        used: 27,
        resets: 4 * 1440,
        primary: true,
      },
    ],
    banked: { label: "Reset Credit", count: 0, expiries: [] },
  },
  {
    id: "cu-1",
    provider: "cursor",
    name: "Personal",
    plan: "Pro",
    identity: null,
    status: "active",
    refreshed: -11,
    meters: [
      {
        key: "included",
        label: "Included",
        window: "$20 plan",
        used: 17,
        resets: 23 * 1440,
        primary: true,
        words: "cycle_end",
      },
      {
        key: "auto",
        label: "Auto Pool",
        window: "billing cycle",
        used: 19,
        resets: 23 * 1440,
        words: "with_cycle",
      },
      {
        key: "api",
        label: "API Pool",
        window: "billing cycle",
        used: 6,
        resets: 23 * 1440,
        words: "with_cycle",
      },
    ],
    balances: [{ label: "On-Demand Spend", value: 0, unit: "usd" }],
  },
  {
    id: "cu-2",
    provider: "cursor",
    name: "Teams Seat",
    plan: "Teams",
    identity: "maverick@acme.example",
    status: "active",
    refreshed: -7,
    meters: [
      {
        key: "included",
        label: "Included",
        window: "$40 plan",
        used: 72,
        resets: 9 * 1440,
        primary: true,
        words: "cycle_end",
      },
      {
        key: "auto",
        label: "Auto Pool",
        window: "billing cycle",
        used: 55,
        resets: 9 * 1440,
        words: "with_cycle",
      },
      {
        key: "api",
        label: "API Pool",
        window: "billing cycle",
        used: 40,
        resets: 9 * 1440,
        words: "with_cycle",
      },
    ],
    balances: [{ label: "On-Demand Spend", value: 12.4, unit: "usd" }],
  },
  {
    id: "gk-1",
    provider: "grok",
    name: "Personal",
    plan: "X Premium",
    identity: null,
    status: "active",
    refreshed: -3,
    meters: [
      {
        key: "weekly",
        label: "Weekly Pool",
        window: "7 days",
        used: 0,
        resets: 6 * 1440 + 660,
        primary: true,
      },
    ],
    balances: [{ label: "Prepaid", value: 0, unit: "credits" }],
  },
  {
    id: "gk-2",
    provider: "grok",
    name: "Work",
    plan: "SuperGrok",
    identity: "maverick@acme.example",
    status: "active",
    refreshed: -5,
    meters: [
      {
        key: "weekly",
        label: "Weekly Pool",
        window: "7 days",
        used: 58,
        resets: 3 * 1440 + 120,
        primary: true,
      },
    ],
    balances: [{ label: "Prepaid", value: 0, unit: "credits" }],
  },
  {
    id: "ag-1",
    provider: "antigravity",
    name: "Personal",
    plan: "Starter Quota",
    identity: "maverick@example.com",
    status: "active",
    refreshed: -8,
    meters: [
      {
        key: "gemini",
        label: "Gemini",
        window: "weekly",
        used: 0,
        resets: 6 * 1440 + 1380,
        primary: true,
      },
      { key: "3p", label: "Claude and GPT", window: "weekly", used: 0, resets: 6 * 1440 + 1380 },
    ],
  },
  {
    id: "cp-1",
    provider: "copilot",
    name: "Personal",
    plan: null,
    identity: "maverick-gh",
    status: "disconnected",
    refreshed: -2 * 1440,
    meters: [
      {
        key: "credits",
        label: "AI Credits",
        window: "monthly",
        used: 0.8,
        resets: 29 * 1440,
        primary: true,
      },
    ],
  },
  {
    id: "vc-1",
    provider: "vercel_ai_gateway",
    name: "Team",
    plan: null,
    identity: "Key ending in 7f3a",
    status: "active",
    refreshed: -11,
    meters: [],
    balances: [{ label: "Credit Balance", value: 4.99, unit: "credits", of: 5 }],
  },
  {
    id: "vc-2",
    provider: "vercel_ai_gateway",
    name: "Staging",
    plan: null,
    identity: "Key ending in 2c9e",
    status: "active",
    refreshed: -8,
    meters: [],
    balances: [{ label: "Credit Balance", value: 12.4, unit: "credits", of: 20 }],
  },
];
