/**
 * Compile the server into dist/headroom with the built web UI embedded.
 *
 * Bun embeds a file only when the bundle imports it with `with { type: "file" }`, so this writes a
 * throwaway module (dist/embedded-assets.ts, gitignored) that imports every file in apps/web/dist,
 * hands the URL-path -> embedded-path map to the server, and a dist/server-entry.ts that loads it before the server. Run `bun run web:build` first.
 */
import { existsSync, readdirSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const webDist = join(root, "apps/web/dist");
const entry = join(root, "dist/server-entry.ts");

if (!existsSync(join(webDist, "index.html"))) {
  throw new Error("apps/web/dist/index.html is missing; run `bun run web:build` first");
}

const files = readdirSync(webDist, { recursive: true, withFileTypes: true })
  .filter((item) => item.isFile())
  .map((item) => relative(webDist, join(item.parentPath, item.name)).split("\\").join("/"))
  .toSorted();

const imports = files.map(
  (file, i) => `import f${i} from ${JSON.stringify(join(webDist, file))} with { type: "file" };`,
);
const map = files.map((file, i) => `  ${JSON.stringify(file)}: f${i},`);
const source = `// Generated by scripts/build-server.ts. Do not edit.
import { registerEmbeddedAssets } from "../apps/server/src/web-assets.ts";
${imports.join("\n")}

registerEmbeddedAssets({
${map.join("\n")}
});

`;
await Bun.write(join(root, "dist/embedded-assets.ts"), source);
// Static imports evaluate in order, so the assets register before the server starts.
await Bun.write(
  entry,
  `// Generated by scripts/build-server.ts. Do not edit.
import "./embedded-assets.ts";
import "../apps/server/src/index.ts";
`,
);

const result = Bun.spawnSync(
  [
    process.execPath,
    "build",
    "--compile",
    "--minify",
    "--sourcemap",
    entry,
    "--outfile",
    join(root, "dist/headroom"),
    // Extra flags such as --target=bun-linux-x64 pass through (the Dockerfile uses this).
    ...Bun.argv.slice(2),
  ],
  { cwd: root, stdout: "inherit", stderr: "inherit" },
);
process.exit(result.exitCode);
