#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: npm and PyPI publishing for the headroomhq packages. See packaging/README.md.
#
#   scripts/publishing-wizard.sh before   # before merging the release that should publish first
#   scripts/publishing-wizard.sh after    # once that release has published to npm
#
# No value is written to a file. The npm token goes straight into the NPM_TOKEN secret.
# ──────────────────────────────────────────────────────────────────────────

REPO="amitray007/headroom"
PACKAGES=(headroomhq-darwin-arm64 headroomhq-darwin-x64 headroomhq-linux-x64 headroomhq-linux-arm64 headroomhq)
WORKFLOWS=(release-please.yml packages.yml)
cd "$(dirname "$0")/.."

case "${1:-}" in
before)
  TOTAL_STAGES=5
  banner "Headroom: npm and PyPI publishing, part 1 of 2"

  stage "npm: your account"
  say "The packages publish under your npm account."
  open_url "https://www.npmjs.com/signup"
  step "Sign up, or sign in if you already have an account."
  step "Turn on two-factor authentication: profile picture > Account > Two-Factor Authentication."
  pause "Press Enter when you are signed in with 2FA on."

  stage "npm: a token for the first publish"
  say "npm can trust a workflow only for a package that exists."
  say "So the first release publishes with a short-lived token. Part 2 replaces it."
  open_url "https://www.npmjs.com/"
  step "Profile picture > Access Tokens > Generate New Token."
  step "Token name: headroom first publish"
  step "Tick 'Bypass two-factor authentication'. CI cannot answer a 2FA prompt."
  step "Packages and scopes > Permissions: Read and write (publish and stage)."
  step "Select Packages: All Packages. The headroomhq packages do not exist yet."
  step "Expiration: 7 days."
  step "Generate Token, then copy it from the top of the page."
  ask_secret NPM_TOKEN "Paste the npm token (hidden):"
  if [[ -z "$NPM_TOKEN" ]]; then warn "No token entered. Run this stage again later."; else set_secret NPM_TOKEN "$NPM_TOKEN"; fi
  unset NPM_TOKEN
  set_var NPM_PUBLISH true

  stage "PyPI: your account"
  open_url "https://pypi.org/account/register/"
  step "Register, or sign in if you already have an account."
  step "PyPI asks you to turn on two-factor authentication. Do it before the next stage."
  pause "Press Enter when you are signed in with 2FA on."

  stage "PyPI: trust the release workflow"
  say "A pending publisher lets the first release create the headroomhq project. No token is needed."
  open_url "https://pypi.org/manage/account/publishing/"
  step "Under 'Add a new pending publisher', pick GitHub."
  step "PyPI Project Name: headroomhq"
  step "Owner: amitray007"
  step "Repository name: headroom"
  step "Workflow name: release-please.yml"
  step "Environment name: pypi"
  step "Click Add."
  if confirm "Did PyPI list the pending publisher?"; then
    set_var PYPI_PUBLISH true
  else
    SKIPPED+=("PyPI pending publisher, then: gh variable set PYPI_PUBLISH --body true")
    warn "PYPI_PUBLISH stays off, so the release skips PyPI."
  fi

  stage "Release"
  say "The next release now publishes to npm and PyPI."
  say "Merge the release pull request when you are ready:"
  open_url "https://github.com/$REPO/pulls?q=is%3Apr+is%3Aopen+release"
  say "When the Release run has finished, run part 2:"
  say "  scripts/publishing-wizard.sh after"
  pause "Press Enter to finish."
  finish
  ;;

after)
  TOTAL_STAGES=4
  banner "Headroom: npm and PyPI publishing, part 2 of 2"

  stage "npm: check the first publish"
  missing=()
  for name in "${PACKAGES[@]}"; do
    if version=$(npm view "$name" version 2>/dev/null) && [[ -n "$version" ]]; then
      printf '  %s✓%s %s %s\n' "$GREEN" "$RESET" "$name" "$version"
    else
      printf '  %s✗%s %s is not on npm\n' "$RED" "$RESET" "$name"
      missing+=("$name")
    fi
  done
  if (( ${#missing[@]} )); then
    warn "Some packages are missing. Check the Packages job of the Release run:"
    open_url "https://github.com/$REPO/actions/workflows/release-please.yml"
    note "If npm refused the token for a new package name, ask the agent to publish them from your machine."
    exit 1
  fi
  pause "Press Enter to continue."

  stage "npm: sign in on this machine"
  say "Setting up trusted publishing needs your own npm login, with 2FA."
  if npm whoami >/dev/null 2>&1; then
    note "Signed in as $(npm whoami)."
  else
    npm login --auth-type=web
  fi
  pause "Press Enter to continue."

  stage "npm: trust the workflows"
  say "Each package trusts release-please.yml (releases) and packages.yml (runs by hand)."
  say "npm may ask for 2FA for each one."
  for name in "${PACKAGES[@]}"; do
    for file in "${WORKFLOWS[@]}"; do
      printf '\n  %s%s ← %s%s\n' "$BOLD" "$name" "$file" "$RESET"
      if ! npm trust github "$name" --file "$file" --repository "$REPO" --allow-publish --yes; then
        SKIPPED+=("npm trust github $name --file $file --repository $REPO --allow-publish")
        warn "Not set. It may exist already: npm trust list $name"
      fi
    done
  done
  pause "Press Enter to continue."

  stage "npm: delete the first-publish token"
  say "Releases now publish with trusted publishing. The token is no longer needed."
  open_url "https://www.npmjs.com/"
  step "Profile picture > Access Tokens."
  step "Delete the token named 'headroom first publish'."
  if confirm "Remove the NPM_TOKEN secret from the repository too?"; then
    if gh secret delete NPM_TOKEN --repo "$REPO" >/dev/null 2>&1; then
      printf '  %s✓ deleted%s GitHub secret NPM_TOKEN\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("gh secret delete NPM_TOKEN --repo $REPO")
    fi
  fi
  pause "Press Enter to finish."
  finish
  ;;

*)
  printf 'Usage: %s before|after\n' "$0" >&2
  exit 2
  ;;
esac
