#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: npm and PyPI publishing for the headroomhq packages. See packaging/README.md.
#
#   scripts/publishing-wizard.sh before   # before merging the release that should publish first
#   scripts/publishing-wizard.sh after    # once that release is out
#
# No token is created. npm's first publish happens here, signed in with 2FA; every later release
# publishes from GitHub Actions with trusted publishing (OIDC).
# ──────────────────────────────────────────────────────────────────────────

REPO="amitray007/headroom"
PACKAGES=(headroomhq-darwin-arm64 headroomhq-darwin-x64 headroomhq-linux-x64 headroomhq-linux-arm64 headroomhq)
WORKFLOWS=(release-please.yml packages.yml)
cd "$(dirname "$0")/.."

case "${1:-}" in
before)
  TOTAL_STAGES=4
  banner "Headroom: npm and PyPI publishing, part 1 of 2"

  stage "npm: your account"
  say "The packages publish under your npm account. Part 2 publishes them for the first time."
  open_url "https://www.npmjs.com/signup"
  step "Sign up, or sign in if you already have an account."
  step "Turn on two-factor authentication: profile picture > Account > Two-Factor Authentication."
  pause "Press Enter when you are signed in with 2FA on."

  stage "PyPI: your account"
  open_url "https://pypi.org/account/register/"
  step "Register, or sign in if you already have an account."
  step "PyPI asks you to turn on two-factor authentication. Do it before the next stage."
  pause "Press Enter when you are signed in with 2FA on."

  stage "PyPI: trust the publishing workflow"
  say "A pending publisher lets the first release create the headroomhq project. No token is needed."
  open_url "https://pypi.org/manage/account/publishing/"
  step "Under 'Add a new pending publisher', pick GitHub."
  step "PyPI Project Name: headroomhq"
  step "Owner: amitray007"
  step "Repository name: headroom"
  step "Workflow name: packages.yml"
  note "PyPI checks the file that holds the publish job. Releases call packages.yml from release-please.yml."
  step "Environment name: pypi"
  step "Click Add."
  if confirm "Did PyPI list the pending publisher?"; then
    set_var PYPI_PUBLISH true
  else
    SKIPPED+=("PyPI pending publisher, then: gh variable set PYPI_PUBLISH --body true")
    warn "PYPI_PUBLISH stays off, so the release skips PyPI."
  fi

  stage "Release"
  say "The next release publishes to PyPI. npm waits for part 2."
  say "Merge the release pull request when you are ready:"
  open_url "https://github.com/$REPO/pulls?q=is%3Apr+is%3Aopen+release"
  say "When the Release run has finished, run part 2:"
  say "  scripts/publishing-wizard.sh after"
  pause "Press Enter to finish."
  finish
  ;;

after)
  TOTAL_STAGES=5
  banner "Headroom: npm and PyPI publishing, part 2 of 2"

  stage "npm: build the packages"
  VERSION=$(gh release view --repo "$REPO" --json tagName --jq .tagName)
  VERSION="${VERSION#v}"
  say "Building the five npm packages from the v$VERSION release files."
  WORK=$(mktemp -d)
  gh release download "v$VERSION" --repo "$REPO" --dir "$WORK/assets" --pattern 'headroom-*.tar.gz' --pattern SHA256SUMS
  mise exec -- bun scripts/package-npm.ts --version "$VERSION" --assets "$WORK/assets" --out "$WORK/npm" >/dev/null
  mkdir -p "$WORK/tgz"
  for dir in "$WORK"/npm/*/; do (cd "$dir" && npm pack --silent --pack-destination "$WORK/tgz" >/dev/null); done
  for name in "${PACKAGES[@]}"; do
    [[ -f "$WORK/tgz/$name-$VERSION.tgz" ]] || { printf '  %s✗%s %s-%s.tgz is missing in %s\n' "$RED" "$RESET" "$name" "$VERSION" "$WORK/tgz"; exit 1; }
    printf '  %s✓%s %s-%s.tgz\n' "$GREEN" "$RESET" "$name" "$VERSION"
  done
  pause "Press Enter to continue."

  stage "npm: sign in"
  say "Sign in with your own account. npm asks for 2FA in the browser."
  if npm whoami >/dev/null 2>&1; then
    note "Signed in as $(npm whoami)."
  else
    npm login --auth-type=web
  fi
  pause "Press Enter to continue."

  stage "npm: first publish"
  say "Publishing v$VERSION. The platform packages go first, headroomhq last."
  say "npm may ask you to approve each publish in the browser."
  if confirm "Publish the five packages to npm now? Published versions are public and permanent."; then
    for name in "${PACKAGES[@]}"; do
      if npm view "$name@$VERSION" version >/dev/null 2>&1; then
        note "$name@$VERSION is already on npm."
        continue
      fi
      printf '\n  %s%s@%s%s\n' "$BOLD" "$name" "$VERSION" "$RESET"
      npm publish "$WORK/tgz/$name-$VERSION.tgz" --access public --auth-type=web || { warn "Publishing $name failed. Fix it and run part 2 again."; exit 1; }
    done
  else
    warn "Nothing published. Run part 2 again when you are ready."
    exit 1
  fi
  pause "Press Enter to continue."

  stage "npm: trust the workflows"
  say "Each package trusts release-please.yml (releases) and packages.yml (runs by hand)."
  say "npm may ask for 2FA for each one."
  for name in "${PACKAGES[@]}"; do
    for file in "${WORKFLOWS[@]}"; do
      printf '\n  %s%s ← %s%s\n' "$BOLD" "$name" "$file" "$RESET"
      if ! npm trust github "$name" --file "$file" --repository "$REPO" --allow-publish --yes; then
        SKIPPED+=("npm trust github $name --file $file --repository $REPO --allow-publish")
        warn "Not set. It may exist already: npm trust list $name"
      fi
    done
  done
  pause "Press Enter to continue."

  stage "npm: publish from releases"
  say "Every later release now publishes to npm from GitHub Actions, with no token."
  set_var NPM_PUBLISH true
  rm -rf "$WORK"
  pause "Press Enter to finish."
  finish
  ;;

*)
  printf 'Usage: %s before|after\n' "$0" >&2
  exit 2
  ;;
esac
